name: "TurboRepo Remote Cache Server"
description: "Runs a TurboRepo remote cache server based on ducktors/turborepo-remote-cache."
author: trappar
branding:
  icon: server
  color: blue
inputs:
  storage-provider:
    description: "Possible values are s3, google-cloud-storage, or azure-blob-storage. Local storage is technically supported but is useless."
    required: true
  storage-path:
    description: "The name of s3, google-cloud-storage, or azure-blob-storage bucket."
    required: true
  team-id:
    description: "Sets the TURBO_TEAM env variable, which controls the directory where cache entries will be saved."
    required: false
    default: "ci"
  host:
    description: "Used to set the TURBO_API env variable."
    required: false
    default: "0.0.0.0"
  port:
    description: "Sets the port the server will listen on, and is added to the end of the TURBO_API env variable."
    required: false
runs:
  using: "node20"
  main: "dist/start/index.js"
  post: "dist/post/index.js"
